#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteClothesStore.ModelsLinqToSQL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QUANAOSTORE")]
	public partial class LinqToSQLDataContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertThanhVien(ThanhVien instance);
    partial void UpdateThanhVien(ThanhVien instance);
    partial void DeleteThanhVien(ThanhVien instance);
    partial void InsertNhaSX(NhaSX instance);
    partial void UpdateNhaSX(NhaSX instance);
    partial void DeleteNhaSX(NhaSX instance);
    partial void InsertNhaCC(NhaCC instance);
    partial void UpdateNhaCC(NhaCC instance);
    partial void DeleteNhaCC(NhaCC instance);
    partial void InsertLoaiTV(LoaiTV instance);
    partial void UpdateLoaiTV(LoaiTV instance);
    partial void DeleteLoaiTV(LoaiTV instance);
    partial void InsertLoaiSanPham(LoaiSanPham instance);
    partial void UpdateLoaiSanPham(LoaiSanPham instance);
    partial void DeleteLoaiSanPham(LoaiSanPham instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertDonDatHang(DonDatHang instance);
    partial void UpdateDonDatHang(DonDatHang instance);
    partial void DeleteDonDatHang(DonDatHang instance);
    partial void InsertCTSanPham(CTSanPham instance);
    partial void UpdateCTSanPham(CTSanPham instance);
    partial void DeleteCTSanPham(CTSanPham instance);
    partial void InsertCTPhieuNhap(CTPhieuNhap instance);
    partial void UpdateCTPhieuNhap(CTPhieuNhap instance);
    partial void DeleteCTPhieuNhap(CTPhieuNhap instance);
    partial void InsertCTDonDatHang(CTDonDatHang instance);
    partial void UpdateCTDonDatHang(CTDonDatHang instance);
    partial void DeleteCTDonDatHang(CTDonDatHang instance);
    partial void InsertBangSanPham(BangSanPham instance);
    partial void UpdateBangSanPham(BangSanPham instance);
    partial void DeleteBangSanPham(BangSanPham instance);
    partial void InsertBangPhieuNhap(BangPhieuNhap instance);
    partial void UpdateBangPhieuNhap(BangPhieuNhap instance);
    partial void DeleteBangPhieuNhap(BangPhieuNhap instance);
    #endregion
		
		public LinqToSQLDataContextDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QUANAOSTOREConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToSQLDataContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToSQLDataContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToSQLDataContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToSQLDataContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ThanhVien> ThanhViens
		{
			get
			{
				return this.GetTable<ThanhVien>();
			}
		}
		
		public System.Data.Linq.Table<NhaSX> NhaSXes
		{
			get
			{
				return this.GetTable<NhaSX>();
			}
		}
		
		public System.Data.Linq.Table<NhaCC> NhaCCs
		{
			get
			{
				return this.GetTable<NhaCC>();
			}
		}
		
		public System.Data.Linq.Table<LoaiTV> LoaiTVs
		{
			get
			{
				return this.GetTable<LoaiTV>();
			}
		}
		
		public System.Data.Linq.Table<LoaiSanPham> LoaiSanPhams
		{
			get
			{
				return this.GetTable<LoaiSanPham>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<DonDatHang> DonDatHangs
		{
			get
			{
				return this.GetTable<DonDatHang>();
			}
		}
		
		public System.Data.Linq.Table<CTSanPham> CTSanPhams
		{
			get
			{
				return this.GetTable<CTSanPham>();
			}
		}
		
		public System.Data.Linq.Table<CTPhieuNhap> CTPhieuNhaps
		{
			get
			{
				return this.GetTable<CTPhieuNhap>();
			}
		}
		
		public System.Data.Linq.Table<CTDonDatHang> CTDonDatHangs
		{
			get
			{
				return this.GetTable<CTDonDatHang>();
			}
		}
		
		public System.Data.Linq.Table<BangSanPham> BangSanPhams
		{
			get
			{
				return this.GetTable<BangSanPham>();
			}
		}
		
		public System.Data.Linq.Table<BangPhieuNhap> BangPhieuNhaps
		{
			get
			{
				return this.GetTable<BangPhieuNhap>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThanhVien")]
	public partial class ThanhVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTV;
		
		private string _TaiKhoan;
		
		private string _MatKhau;
		
		private string _HoTen;
		
		private string _DiaChi;
		
		private string _Email;
		
		private int _SDT;
		
		private string _CauHoi;
		
		private int _MaLoaiTV;
		
		private EntitySet<KhachHang> _KhachHangs;
		
		private EntityRef<LoaiTV> _LoaiTV;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTVChanging(int value);
    partial void OnMaTVChanged();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSDTChanging(int value);
    partial void OnSDTChanged();
    partial void OnCauHoiChanging(string value);
    partial void OnCauHoiChanged();
    partial void OnMaLoaiTVChanging(int value);
    partial void OnMaLoaiTVChanged();
    #endregion
		
		public ThanhVien()
		{
			this._KhachHangs = new EntitySet<KhachHang>(new Action<KhachHang>(this.attach_KhachHangs), new Action<KhachHang>(this.detach_KhachHangs));
			this._LoaiTV = default(EntityRef<LoaiTV>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaTV
		{
			get
			{
				return this._MaTV;
			}
			set
			{
				if ((this._MaTV != value))
				{
					this.OnMaTVChanging(value);
					this.SendPropertyChanging();
					this._MaTV = value;
					this.SendPropertyChanged("MaTV");
					this.OnMaTVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Int NOT NULL")]
		public int SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CauHoi", DbType="NVarChar(50)")]
		public string CauHoi
		{
			get
			{
				return this._CauHoi;
			}
			set
			{
				if ((this._CauHoi != value))
				{
					this.OnCauHoiChanging(value);
					this.SendPropertyChanging();
					this._CauHoi = value;
					this.SendPropertyChanged("CauHoi");
					this.OnCauHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiTV", DbType="Int NOT NULL")]
		public int MaLoaiTV
		{
			get
			{
				return this._MaLoaiTV;
			}
			set
			{
				if ((this._MaLoaiTV != value))
				{
					if (this._LoaiTV.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiTVChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiTV = value;
					this.SendPropertyChanged("MaLoaiTV");
					this.OnMaLoaiTVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThanhVien_KhachHang", Storage="_KhachHangs", ThisKey="MaTV", OtherKey="MaTV")]
		public EntitySet<KhachHang> KhachHangs
		{
			get
			{
				return this._KhachHangs;
			}
			set
			{
				this._KhachHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiTV_ThanhVien", Storage="_LoaiTV", ThisKey="MaLoaiTV", OtherKey="MaLoaiTV", IsForeignKey=true)]
		public LoaiTV LoaiTV
		{
			get
			{
				return this._LoaiTV.Entity;
			}
			set
			{
				LoaiTV previousValue = this._LoaiTV.Entity;
				if (((previousValue != value) 
							|| (this._LoaiTV.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiTV.Entity = null;
						previousValue.ThanhViens.Remove(this);
					}
					this._LoaiTV.Entity = value;
					if ((value != null))
					{
						value.ThanhViens.Add(this);
						this._MaLoaiTV = value.MaLoaiTV;
					}
					else
					{
						this._MaLoaiTV = default(int);
					}
					this.SendPropertyChanged("LoaiTV");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KhachHangs(KhachHang entity)
		{
			this.SendPropertyChanging();
			entity.ThanhVien = this;
		}
		
		private void detach_KhachHangs(KhachHang entity)
		{
			this.SendPropertyChanging();
			entity.ThanhVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhaSX")]
	public partial class NhaSX : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNSX;
		
		private string _TenNSX;
		
		private string _ThongTin;
		
		private string _Logo;
		
		private EntitySet<BangSanPham> _BangSanPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNSXChanging(int value);
    partial void OnMaNSXChanged();
    partial void OnTenNSXChanging(string value);
    partial void OnTenNSXChanged();
    partial void OnThongTinChanging(string value);
    partial void OnThongTinChanged();
    partial void OnLogoChanging(string value);
    partial void OnLogoChanged();
    #endregion
		
		public NhaSX()
		{
			this._BangSanPhams = new EntitySet<BangSanPham>(new Action<BangSanPham>(this.attach_BangSanPhams), new Action<BangSanPham>(this.detach_BangSanPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNSX", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNSX
		{
			get
			{
				return this._MaNSX;
			}
			set
			{
				if ((this._MaNSX != value))
				{
					this.OnMaNSXChanging(value);
					this.SendPropertyChanging();
					this._MaNSX = value;
					this.SendPropertyChanged("MaNSX");
					this.OnMaNSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNSX", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenNSX
		{
			get
			{
				return this._TenNSX;
			}
			set
			{
				if ((this._TenNSX != value))
				{
					this.OnTenNSXChanging(value);
					this.SendPropertyChanging();
					this._TenNSX = value;
					this.SendPropertyChanged("TenNSX");
					this.OnTenNSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThongTin", DbType="NVarChar(50)")]
		public string ThongTin
		{
			get
			{
				return this._ThongTin;
			}
			set
			{
				if ((this._ThongTin != value))
				{
					this.OnThongTinChanging(value);
					this.SendPropertyChanging();
					this._ThongTin = value;
					this.SendPropertyChanged("ThongTin");
					this.OnThongTinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Logo", DbType="NVarChar(50)")]
		public string Logo
		{
			get
			{
				return this._Logo;
			}
			set
			{
				if ((this._Logo != value))
				{
					this.OnLogoChanging(value);
					this.SendPropertyChanging();
					this._Logo = value;
					this.SendPropertyChanged("Logo");
					this.OnLogoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaSX_BangSanPham", Storage="_BangSanPhams", ThisKey="MaNSX", OtherKey="MaNSX")]
		public EntitySet<BangSanPham> BangSanPhams
		{
			get
			{
				return this._BangSanPhams;
			}
			set
			{
				this._BangSanPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BangSanPhams(BangSanPham entity)
		{
			this.SendPropertyChanging();
			entity.NhaSX = this;
		}
		
		private void detach_BangSanPhams(BangSanPham entity)
		{
			this.SendPropertyChanging();
			entity.NhaSX = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhaCC")]
	public partial class NhaCC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNCC;
		
		private string _TenNCC;
		
		private string _DiaChi;
		
		private string _Email;
		
		private int _SDT;
		
		private EntitySet<BangSanPham> _BangSanPhams;
		
		private EntitySet<BangPhieuNhap> _BangPhieuNhaps;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNCCChanging(int value);
    partial void OnMaNCCChanged();
    partial void OnTenNCCChanging(string value);
    partial void OnTenNCCChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSDTChanging(int value);
    partial void OnSDTChanged();
    #endregion
		
		public NhaCC()
		{
			this._BangSanPhams = new EntitySet<BangSanPham>(new Action<BangSanPham>(this.attach_BangSanPhams), new Action<BangSanPham>(this.detach_BangSanPhams));
			this._BangPhieuNhaps = new EntitySet<BangPhieuNhap>(new Action<BangPhieuNhap>(this.attach_BangPhieuNhaps), new Action<BangPhieuNhap>(this.detach_BangPhieuNhaps));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNCC", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNCC
		{
			get
			{
				return this._MaNCC;
			}
			set
			{
				if ((this._MaNCC != value))
				{
					this.OnMaNCCChanging(value);
					this.SendPropertyChanging();
					this._MaNCC = value;
					this.SendPropertyChanged("MaNCC");
					this.OnMaNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNCC", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenNCC
		{
			get
			{
				return this._TenNCC;
			}
			set
			{
				if ((this._TenNCC != value))
				{
					this.OnTenNCCChanging(value);
					this.SendPropertyChanging();
					this._TenNCC = value;
					this.SendPropertyChanged("TenNCC");
					this.OnTenNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Int NOT NULL")]
		public int SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaCC_BangSanPham", Storage="_BangSanPhams", ThisKey="MaNCC", OtherKey="MaNCC")]
		public EntitySet<BangSanPham> BangSanPhams
		{
			get
			{
				return this._BangSanPhams;
			}
			set
			{
				this._BangSanPhams.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaCC_BangPhieuNhap", Storage="_BangPhieuNhaps", ThisKey="MaNCC", OtherKey="MaNCC")]
		public EntitySet<BangPhieuNhap> BangPhieuNhaps
		{
			get
			{
				return this._BangPhieuNhaps;
			}
			set
			{
				this._BangPhieuNhaps.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BangSanPhams(BangSanPham entity)
		{
			this.SendPropertyChanging();
			entity.NhaCC = this;
		}
		
		private void detach_BangSanPhams(BangSanPham entity)
		{
			this.SendPropertyChanging();
			entity.NhaCC = null;
		}
		
		private void attach_BangPhieuNhaps(BangPhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.NhaCC = this;
		}
		
		private void detach_BangPhieuNhaps(BangPhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.NhaCC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiTV")]
	public partial class LoaiTV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaLoaiTV;
		
		private string _TenLoai;
		
		private System.Nullable<double> _UuDai;
		
		private EntitySet<ThanhVien> _ThanhViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiTVChanging(int value);
    partial void OnMaLoaiTVChanged();
    partial void OnTenLoaiChanging(string value);
    partial void OnTenLoaiChanged();
    partial void OnUuDaiChanging(System.Nullable<double> value);
    partial void OnUuDaiChanged();
    #endregion
		
		public LoaiTV()
		{
			this._ThanhViens = new EntitySet<ThanhVien>(new Action<ThanhVien>(this.attach_ThanhViens), new Action<ThanhVien>(this.detach_ThanhViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiTV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaLoaiTV
		{
			get
			{
				return this._MaLoaiTV;
			}
			set
			{
				if ((this._MaLoaiTV != value))
				{
					this.OnMaLoaiTVChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiTV = value;
					this.SendPropertyChanged("MaLoaiTV");
					this.OnMaLoaiTVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(50)")]
		public string TenLoai
		{
			get
			{
				return this._TenLoai;
			}
			set
			{
				if ((this._TenLoai != value))
				{
					this.OnTenLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenLoai = value;
					this.SendPropertyChanged("TenLoai");
					this.OnTenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UuDai", DbType="Float")]
		public System.Nullable<double> UuDai
		{
			get
			{
				return this._UuDai;
			}
			set
			{
				if ((this._UuDai != value))
				{
					this.OnUuDaiChanging(value);
					this.SendPropertyChanging();
					this._UuDai = value;
					this.SendPropertyChanged("UuDai");
					this.OnUuDaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiTV_ThanhVien", Storage="_ThanhViens", ThisKey="MaLoaiTV", OtherKey="MaLoaiTV")]
		public EntitySet<ThanhVien> ThanhViens
		{
			get
			{
				return this._ThanhViens;
			}
			set
			{
				this._ThanhViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ThanhViens(ThanhVien entity)
		{
			this.SendPropertyChanging();
			entity.LoaiTV = this;
		}
		
		private void detach_ThanhViens(ThanhVien entity)
		{
			this.SendPropertyChanging();
			entity.LoaiTV = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiSanPham")]
	public partial class LoaiSanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaLoai;
		
		private string _TenLoai;
		
		private string _Logo;
		
		private string _BiDanh;
		
		private EntitySet<BangSanPham> _BangSanPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiChanging(int value);
    partial void OnMaLoaiChanged();
    partial void OnTenLoaiChanging(string value);
    partial void OnTenLoaiChanged();
    partial void OnLogoChanging(string value);
    partial void OnLogoChanged();
    partial void OnBiDanhChanging(string value);
    partial void OnBiDanhChanged();
    #endregion
		
		public LoaiSanPham()
		{
			this._BangSanPhams = new EntitySet<BangSanPham>(new Action<BangSanPham>(this.attach_BangSanPhams), new Action<BangSanPham>(this.detach_BangSanPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaLoai
		{
			get
			{
				return this._MaLoai;
			}
			set
			{
				if ((this._MaLoai != value))
				{
					this.OnMaLoaiChanging(value);
					this.SendPropertyChanging();
					this._MaLoai = value;
					this.SendPropertyChanged("MaLoai");
					this.OnMaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenLoai
		{
			get
			{
				return this._TenLoai;
			}
			set
			{
				if ((this._TenLoai != value))
				{
					this.OnTenLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenLoai = value;
					this.SendPropertyChanged("TenLoai");
					this.OnTenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Logo", DbType="NVarChar(50)")]
		public string Logo
		{
			get
			{
				return this._Logo;
			}
			set
			{
				if ((this._Logo != value))
				{
					this.OnLogoChanging(value);
					this.SendPropertyChanging();
					this._Logo = value;
					this.SendPropertyChanged("Logo");
					this.OnLogoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BiDanh", DbType="NVarChar(50)")]
		public string BiDanh
		{
			get
			{
				return this._BiDanh;
			}
			set
			{
				if ((this._BiDanh != value))
				{
					this.OnBiDanhChanging(value);
					this.SendPropertyChanging();
					this._BiDanh = value;
					this.SendPropertyChanged("BiDanh");
					this.OnBiDanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiSanPham_BangSanPham", Storage="_BangSanPhams", ThisKey="MaLoai", OtherKey="MaLoai")]
		public EntitySet<BangSanPham> BangSanPhams
		{
			get
			{
				return this._BangSanPhams;
			}
			set
			{
				this._BangSanPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BangSanPhams(BangSanPham entity)
		{
			this.SendPropertyChanging();
			entity.LoaiSanPham = this;
		}
		
		private void detach_BangSanPhams(BangSanPham entity)
		{
			this.SendPropertyChanging();
			entity.LoaiSanPham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKH;
		
		private string _TenKH;
		
		private string _DiaChi;
		
		private string _Email;
		
		private System.Nullable<int> _SDT;
		
		private int _MaTV;
		
		private EntitySet<DonDatHang> _DonDatHangs;
		
		private EntityRef<ThanhVien> _ThanhVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(int value);
    partial void OnMaKHChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSDTChanging(System.Nullable<int> value);
    partial void OnSDTChanged();
    partial void OnMaTVChanging(int value);
    partial void OnMaTVChanged();
    #endregion
		
		public KhachHang()
		{
			this._DonDatHangs = new EntitySet<DonDatHang>(new Action<DonDatHang>(this.attach_DonDatHangs), new Action<DonDatHang>(this.detach_DonDatHangs));
			this._ThanhVien = default(EntityRef<ThanhVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this.OnTenKHChanging(value);
					this.SendPropertyChanging();
					this._TenKH = value;
					this.SendPropertyChanged("TenKH");
					this.OnTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Int")]
		public System.Nullable<int> SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTV", DbType="Int NOT NULL")]
		public int MaTV
		{
			get
			{
				return this._MaTV;
			}
			set
			{
				if ((this._MaTV != value))
				{
					if (this._ThanhVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTVChanging(value);
					this.SendPropertyChanging();
					this._MaTV = value;
					this.SendPropertyChanged("MaTV");
					this.OnMaTVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_DonDatHang", Storage="_DonDatHangs", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<DonDatHang> DonDatHangs
		{
			get
			{
				return this._DonDatHangs;
			}
			set
			{
				this._DonDatHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThanhVien_KhachHang", Storage="_ThanhVien", ThisKey="MaTV", OtherKey="MaTV", IsForeignKey=true)]
		public ThanhVien ThanhVien
		{
			get
			{
				return this._ThanhVien.Entity;
			}
			set
			{
				ThanhVien previousValue = this._ThanhVien.Entity;
				if (((previousValue != value) 
							|| (this._ThanhVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThanhVien.Entity = null;
						previousValue.KhachHangs.Remove(this);
					}
					this._ThanhVien.Entity = value;
					if ((value != null))
					{
						value.KhachHangs.Add(this);
						this._MaTV = value.MaTV;
					}
					else
					{
						this._MaTV = default(int);
					}
					this.SendPropertyChanged("ThanhVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DonDatHangs(DonDatHang entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_DonDatHangs(DonDatHang entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DonDatHang")]
	public partial class DonDatHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDDH;
		
		private string _TinhTrangDDH;
		
		private System.Nullable<bool> _DaThanhToan;
		
		private System.Nullable<double> _UuDai;
		
		private System.Nullable<bool> _DaHuy;
		
		private System.Nullable<bool> _DaXoa;
		
		private System.Nullable<bool> _DaDat;
		
		private System.Nullable<int> _MaKH;
		
		private System.Nullable<System.DateTime> _NgayDat;
		
		private System.Nullable<System.DateTime> _NgayGiao;
		
		private EntityRef<KhachHang> _KhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDDHChanging(int value);
    partial void OnMaDDHChanged();
    partial void OnTinhTrangDDHChanging(string value);
    partial void OnTinhTrangDDHChanged();
    partial void OnDaThanhToanChanging(System.Nullable<bool> value);
    partial void OnDaThanhToanChanged();
    partial void OnUuDaiChanging(System.Nullable<double> value);
    partial void OnUuDaiChanged();
    partial void OnDaHuyChanging(System.Nullable<bool> value);
    partial void OnDaHuyChanged();
    partial void OnDaXoaChanging(System.Nullable<bool> value);
    partial void OnDaXoaChanged();
    partial void OnDaDatChanging(System.Nullable<bool> value);
    partial void OnDaDatChanged();
    partial void OnMaKHChanging(System.Nullable<int> value);
    partial void OnMaKHChanged();
    partial void OnNgayDatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDatChanged();
    partial void OnNgayGiaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayGiaoChanged();
    #endregion
		
		public DonDatHang()
		{
			this._KhachHang = default(EntityRef<KhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDDH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDDH
		{
			get
			{
				return this._MaDDH;
			}
			set
			{
				if ((this._MaDDH != value))
				{
					this.OnMaDDHChanging(value);
					this.SendPropertyChanging();
					this._MaDDH = value;
					this.SendPropertyChanged("MaDDH");
					this.OnMaDDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrangDDH", DbType="NVarChar(50)")]
		public string TinhTrangDDH
		{
			get
			{
				return this._TinhTrangDDH;
			}
			set
			{
				if ((this._TinhTrangDDH != value))
				{
					this.OnTinhTrangDDHChanging(value);
					this.SendPropertyChanging();
					this._TinhTrangDDH = value;
					this.SendPropertyChanged("TinhTrangDDH");
					this.OnTinhTrangDDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaThanhToan", DbType="Bit")]
		public System.Nullable<bool> DaThanhToan
		{
			get
			{
				return this._DaThanhToan;
			}
			set
			{
				if ((this._DaThanhToan != value))
				{
					this.OnDaThanhToanChanging(value);
					this.SendPropertyChanging();
					this._DaThanhToan = value;
					this.SendPropertyChanged("DaThanhToan");
					this.OnDaThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UuDai", DbType="Float")]
		public System.Nullable<double> UuDai
		{
			get
			{
				return this._UuDai;
			}
			set
			{
				if ((this._UuDai != value))
				{
					this.OnUuDaiChanging(value);
					this.SendPropertyChanging();
					this._UuDai = value;
					this.SendPropertyChanged("UuDai");
					this.OnUuDaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaHuy", DbType="Bit")]
		public System.Nullable<bool> DaHuy
		{
			get
			{
				return this._DaHuy;
			}
			set
			{
				if ((this._DaHuy != value))
				{
					this.OnDaHuyChanging(value);
					this.SendPropertyChanging();
					this._DaHuy = value;
					this.SendPropertyChanged("DaHuy");
					this.OnDaHuyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaXoa", DbType="Bit")]
		public System.Nullable<bool> DaXoa
		{
			get
			{
				return this._DaXoa;
			}
			set
			{
				if ((this._DaXoa != value))
				{
					this.OnDaXoaChanging(value);
					this.SendPropertyChanging();
					this._DaXoa = value;
					this.SendPropertyChanged("DaXoa");
					this.OnDaXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaDat", DbType="Bit")]
		public System.Nullable<bool> DaDat
		{
			get
			{
				return this._DaDat;
			}
			set
			{
				if ((this._DaDat != value))
				{
					this.OnDaDatChanging(value);
					this.SendPropertyChanging();
					this._DaDat = value;
					this.SendPropertyChanged("DaDat");
					this.OnDaDatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int")]
		public System.Nullable<int> MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDat", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDat
		{
			get
			{
				return this._NgayDat;
			}
			set
			{
				if ((this._NgayDat != value))
				{
					this.OnNgayDatChanging(value);
					this.SendPropertyChanging();
					this._NgayDat = value;
					this.SendPropertyChanged("NgayDat");
					this.OnNgayDatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGiao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayGiao
		{
			get
			{
				return this._NgayGiao;
			}
			set
			{
				if ((this._NgayGiao != value))
				{
					this.OnNgayGiaoChanging(value);
					this.SendPropertyChanging();
					this._NgayGiao = value;
					this.SendPropertyChanged("NgayGiao");
					this.OnNgayGiaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_DonDatHang", Storage="_KhachHang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.DonDatHangs.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.DonDatHangs.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(Nullable<int>);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTSanPham")]
	public partial class CTSanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaCT;
		
		private string _KichThuoc;
		
		private System.Nullable<int> _SoLuongTon;
		
		private int _MaSP;
		
		private System.Nullable<bool> _Daxoa;
		
		private EntitySet<CTDonDatHang> _CTDonDatHangs;
		
		private EntityRef<BangSanPham> _BangSanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCTChanging(int value);
    partial void OnMaCTChanged();
    partial void OnKichThuocChanging(string value);
    partial void OnKichThuocChanged();
    partial void OnSoLuongTonChanging(System.Nullable<int> value);
    partial void OnSoLuongTonChanged();
    partial void OnMaSPChanging(int value);
    partial void OnMaSPChanged();
    partial void OnDaxoaChanging(System.Nullable<bool> value);
    partial void OnDaxoaChanged();
    #endregion
		
		public CTSanPham()
		{
			this._CTDonDatHangs = new EntitySet<CTDonDatHang>(new Action<CTDonDatHang>(this.attach_CTDonDatHangs), new Action<CTDonDatHang>(this.detach_CTDonDatHangs));
			this._BangSanPham = default(EntityRef<BangSanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaCT
		{
			get
			{
				return this._MaCT;
			}
			set
			{
				if ((this._MaCT != value))
				{
					this.OnMaCTChanging(value);
					this.SendPropertyChanging();
					this._MaCT = value;
					this.SendPropertyChanged("MaCT");
					this.OnMaCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KichThuoc", DbType="NVarChar(50)")]
		public string KichThuoc
		{
			get
			{
				return this._KichThuoc;
			}
			set
			{
				if ((this._KichThuoc != value))
				{
					this.OnKichThuocChanging(value);
					this.SendPropertyChanging();
					this._KichThuoc = value;
					this.SendPropertyChanged("KichThuoc");
					this.OnKichThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongTon", DbType="Int")]
		public System.Nullable<int> SoLuongTon
		{
			get
			{
				return this._SoLuongTon;
			}
			set
			{
				if ((this._SoLuongTon != value))
				{
					this.OnSoLuongTonChanging(value);
					this.SendPropertyChanging();
					this._SoLuongTon = value;
					this.SendPropertyChanged("SoLuongTon");
					this.OnSoLuongTonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSP", DbType="Int NOT NULL")]
		public int MaSP
		{
			get
			{
				return this._MaSP;
			}
			set
			{
				if ((this._MaSP != value))
				{
					if (this._BangSanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSPChanging(value);
					this.SendPropertyChanging();
					this._MaSP = value;
					this.SendPropertyChanged("MaSP");
					this.OnMaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Daxoa", DbType="Bit")]
		public System.Nullable<bool> Daxoa
		{
			get
			{
				return this._Daxoa;
			}
			set
			{
				if ((this._Daxoa != value))
				{
					this.OnDaxoaChanging(value);
					this.SendPropertyChanging();
					this._Daxoa = value;
					this.SendPropertyChanged("Daxoa");
					this.OnDaxoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CTSanPham_CTDonDatHang", Storage="_CTDonDatHangs", ThisKey="MaCT", OtherKey="MaCTSP")]
		public EntitySet<CTDonDatHang> CTDonDatHangs
		{
			get
			{
				return this._CTDonDatHangs;
			}
			set
			{
				this._CTDonDatHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BangSanPham_CTSanPham", Storage="_BangSanPham", ThisKey="MaSP", OtherKey="MaSP", IsForeignKey=true)]
		public BangSanPham BangSanPham
		{
			get
			{
				return this._BangSanPham.Entity;
			}
			set
			{
				BangSanPham previousValue = this._BangSanPham.Entity;
				if (((previousValue != value) 
							|| (this._BangSanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BangSanPham.Entity = null;
						previousValue.CTSanPhams.Remove(this);
					}
					this._BangSanPham.Entity = value;
					if ((value != null))
					{
						value.CTSanPhams.Add(this);
						this._MaSP = value.MaSP;
					}
					else
					{
						this._MaSP = default(int);
					}
					this.SendPropertyChanged("BangSanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTDonDatHangs(CTDonDatHang entity)
		{
			this.SendPropertyChanging();
			entity.CTSanPham = this;
		}
		
		private void detach_CTDonDatHangs(CTDonDatHang entity)
		{
			this.SendPropertyChanging();
			entity.CTSanPham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTPhieuNhap")]
	public partial class CTPhieuNhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCTPN;
		
		private int _MaSP;
		
		private System.Nullable<decimal> _DonGiaNhap;
		
		private System.Nullable<int> _SoLuongNhap;
		
		private EntityRef<BangSanPham> _BangSanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCTPNChanging(string value);
    partial void OnMaCTPNChanged();
    partial void OnMaSPChanging(int value);
    partial void OnMaSPChanged();
    partial void OnDonGiaNhapChanging(System.Nullable<decimal> value);
    partial void OnDonGiaNhapChanged();
    partial void OnSoLuongNhapChanging(System.Nullable<int> value);
    partial void OnSoLuongNhapChanged();
    #endregion
		
		public CTPhieuNhap()
		{
			this._BangSanPham = default(EntityRef<BangSanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCTPN", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCTPN
		{
			get
			{
				return this._MaCTPN;
			}
			set
			{
				if ((this._MaCTPN != value))
				{
					this.OnMaCTPNChanging(value);
					this.SendPropertyChanging();
					this._MaCTPN = value;
					this.SendPropertyChanged("MaCTPN");
					this.OnMaCTPNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSP", DbType="Int NOT NULL")]
		public int MaSP
		{
			get
			{
				return this._MaSP;
			}
			set
			{
				if ((this._MaSP != value))
				{
					if (this._BangSanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSPChanging(value);
					this.SendPropertyChanging();
					this._MaSP = value;
					this.SendPropertyChanged("MaSP");
					this.OnMaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGiaNhap", DbType="Money")]
		public System.Nullable<decimal> DonGiaNhap
		{
			get
			{
				return this._DonGiaNhap;
			}
			set
			{
				if ((this._DonGiaNhap != value))
				{
					this.OnDonGiaNhapChanging(value);
					this.SendPropertyChanging();
					this._DonGiaNhap = value;
					this.SendPropertyChanged("DonGiaNhap");
					this.OnDonGiaNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongNhap", DbType="Int")]
		public System.Nullable<int> SoLuongNhap
		{
			get
			{
				return this._SoLuongNhap;
			}
			set
			{
				if ((this._SoLuongNhap != value))
				{
					this.OnSoLuongNhapChanging(value);
					this.SendPropertyChanging();
					this._SoLuongNhap = value;
					this.SendPropertyChanged("SoLuongNhap");
					this.OnSoLuongNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BangSanPham_CTPhieuNhap", Storage="_BangSanPham", ThisKey="MaSP", OtherKey="MaSP", IsForeignKey=true)]
		public BangSanPham BangSanPham
		{
			get
			{
				return this._BangSanPham.Entity;
			}
			set
			{
				BangSanPham previousValue = this._BangSanPham.Entity;
				if (((previousValue != value) 
							|| (this._BangSanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BangSanPham.Entity = null;
						previousValue.CTPhieuNhaps.Remove(this);
					}
					this._BangSanPham.Entity = value;
					if ((value != null))
					{
						value.CTPhieuNhaps.Add(this);
						this._MaSP = value.MaSP;
					}
					else
					{
						this._MaSP = default(int);
					}
					this.SendPropertyChanged("BangSanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTDonDatHang")]
	public partial class CTDonDatHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaCTDDH;
		
		private System.Nullable<int> _MaDDH;
		
		private int _MaSP;
		
		private string _TenSP;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<decimal> _DonGia;
		
		private System.Nullable<int> _MaCTSP;
		
		private EntityRef<CTSanPham> _CTSanPham;
		
		private EntityRef<BangSanPham> _BangSanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCTDDHChanging(int value);
    partial void OnMaCTDDHChanged();
    partial void OnMaDDHChanging(System.Nullable<int> value);
    partial void OnMaDDHChanged();
    partial void OnMaSPChanging(int value);
    partial void OnMaSPChanged();
    partial void OnTenSPChanging(string value);
    partial void OnTenSPChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnDonGiaChanging(System.Nullable<decimal> value);
    partial void OnDonGiaChanged();
    partial void OnMaCTSPChanging(System.Nullable<int> value);
    partial void OnMaCTSPChanged();
    #endregion
		
		public CTDonDatHang()
		{
			this._CTSanPham = default(EntityRef<CTSanPham>);
			this._BangSanPham = default(EntityRef<BangSanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCTDDH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaCTDDH
		{
			get
			{
				return this._MaCTDDH;
			}
			set
			{
				if ((this._MaCTDDH != value))
				{
					this.OnMaCTDDHChanging(value);
					this.SendPropertyChanging();
					this._MaCTDDH = value;
					this.SendPropertyChanged("MaCTDDH");
					this.OnMaCTDDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDDH", DbType="Int")]
		public System.Nullable<int> MaDDH
		{
			get
			{
				return this._MaDDH;
			}
			set
			{
				if ((this._MaDDH != value))
				{
					this.OnMaDDHChanging(value);
					this.SendPropertyChanging();
					this._MaDDH = value;
					this.SendPropertyChanged("MaDDH");
					this.OnMaDDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSP", DbType="Int NOT NULL")]
		public int MaSP
		{
			get
			{
				return this._MaSP;
			}
			set
			{
				if ((this._MaSP != value))
				{
					if (this._BangSanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSPChanging(value);
					this.SendPropertyChanging();
					this._MaSP = value;
					this.SendPropertyChanged("MaSP");
					this.OnMaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSP", DbType="NVarChar(50)")]
		public string TenSP
		{
			get
			{
				return this._TenSP;
			}
			set
			{
				if ((this._TenSP != value))
				{
					this.OnTenSPChanging(value);
					this.SendPropertyChanging();
					this._TenSP = value;
					this.SendPropertyChanged("TenSP");
					this.OnTenSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Money")]
		public System.Nullable<decimal> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCTSP", DbType="Int")]
		public System.Nullable<int> MaCTSP
		{
			get
			{
				return this._MaCTSP;
			}
			set
			{
				if ((this._MaCTSP != value))
				{
					if (this._CTSanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCTSPChanging(value);
					this.SendPropertyChanging();
					this._MaCTSP = value;
					this.SendPropertyChanged("MaCTSP");
					this.OnMaCTSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CTSanPham_CTDonDatHang", Storage="_CTSanPham", ThisKey="MaCTSP", OtherKey="MaCT", IsForeignKey=true)]
		public CTSanPham CTSanPham
		{
			get
			{
				return this._CTSanPham.Entity;
			}
			set
			{
				CTSanPham previousValue = this._CTSanPham.Entity;
				if (((previousValue != value) 
							|| (this._CTSanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CTSanPham.Entity = null;
						previousValue.CTDonDatHangs.Remove(this);
					}
					this._CTSanPham.Entity = value;
					if ((value != null))
					{
						value.CTDonDatHangs.Add(this);
						this._MaCTSP = value.MaCT;
					}
					else
					{
						this._MaCTSP = default(Nullable<int>);
					}
					this.SendPropertyChanged("CTSanPham");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BangSanPham_CTDonDatHang", Storage="_BangSanPham", ThisKey="MaSP", OtherKey="MaSP", IsForeignKey=true)]
		public BangSanPham BangSanPham
		{
			get
			{
				return this._BangSanPham.Entity;
			}
			set
			{
				BangSanPham previousValue = this._BangSanPham.Entity;
				if (((previousValue != value) 
							|| (this._BangSanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BangSanPham.Entity = null;
						previousValue.CTDonDatHangs.Remove(this);
					}
					this._BangSanPham.Entity = value;
					if ((value != null))
					{
						value.CTDonDatHangs.Add(this);
						this._MaSP = value.MaSP;
					}
					else
					{
						this._MaSP = default(int);
					}
					this.SendPropertyChanged("BangSanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BangSanPham")]
	public partial class BangSanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaSP;
		
		private string _TenSP;
		
		private decimal _Dongia;
		
		private System.Nullable<System.DateTime> _NgapCapNhat;
		
		private string _MoTa;
		
		private System.Nullable<int> _LuotXem;
		
		private System.Nullable<int> _LuotBinhChon;
		
		private System.Nullable<int> _LuotBInhLuan;
		
		private System.Nullable<int> _SoLanMua;
		
		private System.Nullable<double> _GiamGia;
		
		private int _MaNCC;
		
		private int _MaLoai;
		
		private int _MaNSX;
		
		private System.Nullable<bool> _DaXoa;
		
		private string _Anh1;
		
		private string _Anh2;
		
		private string _Anh3;
		
		private string _Anh4;
		
		private string _Anh5;
		
		private EntitySet<CTSanPham> _CTSanPhams;
		
		private EntitySet<CTPhieuNhap> _CTPhieuNhaps;
		
		private EntitySet<CTDonDatHang> _CTDonDatHangs;
		
		private EntityRef<LoaiSanPham> _LoaiSanPham;
		
		private EntityRef<NhaCC> _NhaCC;
		
		private EntityRef<NhaSX> _NhaSX;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSPChanging(int value);
    partial void OnMaSPChanged();
    partial void OnTenSPChanging(string value);
    partial void OnTenSPChanged();
    partial void OnDongiaChanging(decimal value);
    partial void OnDongiaChanged();
    partial void OnNgapCapNhatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgapCapNhatChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnLuotXemChanging(System.Nullable<int> value);
    partial void OnLuotXemChanged();
    partial void OnLuotBinhChonChanging(System.Nullable<int> value);
    partial void OnLuotBinhChonChanged();
    partial void OnLuotBInhLuanChanging(System.Nullable<int> value);
    partial void OnLuotBInhLuanChanged();
    partial void OnSoLanMuaChanging(System.Nullable<int> value);
    partial void OnSoLanMuaChanged();
    partial void OnGiamGiaChanging(System.Nullable<double> value);
    partial void OnGiamGiaChanged();
    partial void OnMaNCCChanging(int value);
    partial void OnMaNCCChanged();
    partial void OnMaLoaiChanging(int value);
    partial void OnMaLoaiChanged();
    partial void OnMaNSXChanging(int value);
    partial void OnMaNSXChanged();
    partial void OnDaXoaChanging(System.Nullable<bool> value);
    partial void OnDaXoaChanged();
    partial void OnAnh1Changing(string value);
    partial void OnAnh1Changed();
    partial void OnAnh2Changing(string value);
    partial void OnAnh2Changed();
    partial void OnAnh3Changing(string value);
    partial void OnAnh3Changed();
    partial void OnAnh4Changing(string value);
    partial void OnAnh4Changed();
    partial void OnAnh5Changing(string value);
    partial void OnAnh5Changed();
    #endregion
		
		public BangSanPham()
		{
			this._CTSanPhams = new EntitySet<CTSanPham>(new Action<CTSanPham>(this.attach_CTSanPhams), new Action<CTSanPham>(this.detach_CTSanPhams));
			this._CTPhieuNhaps = new EntitySet<CTPhieuNhap>(new Action<CTPhieuNhap>(this.attach_CTPhieuNhaps), new Action<CTPhieuNhap>(this.detach_CTPhieuNhaps));
			this._CTDonDatHangs = new EntitySet<CTDonDatHang>(new Action<CTDonDatHang>(this.attach_CTDonDatHangs), new Action<CTDonDatHang>(this.detach_CTDonDatHangs));
			this._LoaiSanPham = default(EntityRef<LoaiSanPham>);
			this._NhaCC = default(EntityRef<NhaCC>);
			this._NhaSX = default(EntityRef<NhaSX>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSP", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaSP
		{
			get
			{
				return this._MaSP;
			}
			set
			{
				if ((this._MaSP != value))
				{
					this.OnMaSPChanging(value);
					this.SendPropertyChanging();
					this._MaSP = value;
					this.SendPropertyChanged("MaSP");
					this.OnMaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenSP
		{
			get
			{
				return this._TenSP;
			}
			set
			{
				if ((this._TenSP != value))
				{
					this.OnTenSPChanging(value);
					this.SendPropertyChanging();
					this._TenSP = value;
					this.SendPropertyChanged("TenSP");
					this.OnTenSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dongia", DbType="Money NOT NULL")]
		public decimal Dongia
		{
			get
			{
				return this._Dongia;
			}
			set
			{
				if ((this._Dongia != value))
				{
					this.OnDongiaChanging(value);
					this.SendPropertyChanging();
					this._Dongia = value;
					this.SendPropertyChanged("Dongia");
					this.OnDongiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgapCapNhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgapCapNhat
		{
			get
			{
				return this._NgapCapNhat;
			}
			set
			{
				if ((this._NgapCapNhat != value))
				{
					this.OnNgapCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NgapCapNhat = value;
					this.SendPropertyChanged("NgapCapNhat");
					this.OnNgapCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuotXem", DbType="Int")]
		public System.Nullable<int> LuotXem
		{
			get
			{
				return this._LuotXem;
			}
			set
			{
				if ((this._LuotXem != value))
				{
					this.OnLuotXemChanging(value);
					this.SendPropertyChanging();
					this._LuotXem = value;
					this.SendPropertyChanged("LuotXem");
					this.OnLuotXemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuotBinhChon", DbType="Int")]
		public System.Nullable<int> LuotBinhChon
		{
			get
			{
				return this._LuotBinhChon;
			}
			set
			{
				if ((this._LuotBinhChon != value))
				{
					this.OnLuotBinhChonChanging(value);
					this.SendPropertyChanging();
					this._LuotBinhChon = value;
					this.SendPropertyChanged("LuotBinhChon");
					this.OnLuotBinhChonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuotBInhLuan", DbType="Int")]
		public System.Nullable<int> LuotBInhLuan
		{
			get
			{
				return this._LuotBInhLuan;
			}
			set
			{
				if ((this._LuotBInhLuan != value))
				{
					this.OnLuotBInhLuanChanging(value);
					this.SendPropertyChanging();
					this._LuotBInhLuan = value;
					this.SendPropertyChanged("LuotBInhLuan");
					this.OnLuotBInhLuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLanMua", DbType="Int")]
		public System.Nullable<int> SoLanMua
		{
			get
			{
				return this._SoLanMua;
			}
			set
			{
				if ((this._SoLanMua != value))
				{
					this.OnSoLanMuaChanging(value);
					this.SendPropertyChanging();
					this._SoLanMua = value;
					this.SendPropertyChanged("SoLanMua");
					this.OnSoLanMuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiamGia", DbType="Float")]
		public System.Nullable<double> GiamGia
		{
			get
			{
				return this._GiamGia;
			}
			set
			{
				if ((this._GiamGia != value))
				{
					this.OnGiamGiaChanging(value);
					this.SendPropertyChanging();
					this._GiamGia = value;
					this.SendPropertyChanged("GiamGia");
					this.OnGiamGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNCC", DbType="Int NOT NULL")]
		public int MaNCC
		{
			get
			{
				return this._MaNCC;
			}
			set
			{
				if ((this._MaNCC != value))
				{
					if (this._NhaCC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNCCChanging(value);
					this.SendPropertyChanging();
					this._MaNCC = value;
					this.SendPropertyChanged("MaNCC");
					this.OnMaNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai", DbType="Int NOT NULL")]
		public int MaLoai
		{
			get
			{
				return this._MaLoai;
			}
			set
			{
				if ((this._MaLoai != value))
				{
					if (this._LoaiSanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiChanging(value);
					this.SendPropertyChanging();
					this._MaLoai = value;
					this.SendPropertyChanged("MaLoai");
					this.OnMaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNSX", DbType="Int NOT NULL")]
		public int MaNSX
		{
			get
			{
				return this._MaNSX;
			}
			set
			{
				if ((this._MaNSX != value))
				{
					if (this._NhaSX.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNSXChanging(value);
					this.SendPropertyChanging();
					this._MaNSX = value;
					this.SendPropertyChanged("MaNSX");
					this.OnMaNSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaXoa", DbType="Bit")]
		public System.Nullable<bool> DaXoa
		{
			get
			{
				return this._DaXoa;
			}
			set
			{
				if ((this._DaXoa != value))
				{
					this.OnDaXoaChanging(value);
					this.SendPropertyChanging();
					this._DaXoa = value;
					this.SendPropertyChanged("DaXoa");
					this.OnDaXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh1", DbType="NVarChar(50)")]
		public string Anh1
		{
			get
			{
				return this._Anh1;
			}
			set
			{
				if ((this._Anh1 != value))
				{
					this.OnAnh1Changing(value);
					this.SendPropertyChanging();
					this._Anh1 = value;
					this.SendPropertyChanged("Anh1");
					this.OnAnh1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh2", DbType="NVarChar(50)")]
		public string Anh2
		{
			get
			{
				return this._Anh2;
			}
			set
			{
				if ((this._Anh2 != value))
				{
					this.OnAnh2Changing(value);
					this.SendPropertyChanging();
					this._Anh2 = value;
					this.SendPropertyChanged("Anh2");
					this.OnAnh2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh3", DbType="NVarChar(50)")]
		public string Anh3
		{
			get
			{
				return this._Anh3;
			}
			set
			{
				if ((this._Anh3 != value))
				{
					this.OnAnh3Changing(value);
					this.SendPropertyChanging();
					this._Anh3 = value;
					this.SendPropertyChanged("Anh3");
					this.OnAnh3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh4", DbType="NVarChar(200)")]
		public string Anh4
		{
			get
			{
				return this._Anh4;
			}
			set
			{
				if ((this._Anh4 != value))
				{
					this.OnAnh4Changing(value);
					this.SendPropertyChanging();
					this._Anh4 = value;
					this.SendPropertyChanged("Anh4");
					this.OnAnh4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh5", DbType="NVarChar(200)")]
		public string Anh5
		{
			get
			{
				return this._Anh5;
			}
			set
			{
				if ((this._Anh5 != value))
				{
					this.OnAnh5Changing(value);
					this.SendPropertyChanging();
					this._Anh5 = value;
					this.SendPropertyChanged("Anh5");
					this.OnAnh5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BangSanPham_CTSanPham", Storage="_CTSanPhams", ThisKey="MaSP", OtherKey="MaSP")]
		public EntitySet<CTSanPham> CTSanPhams
		{
			get
			{
				return this._CTSanPhams;
			}
			set
			{
				this._CTSanPhams.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BangSanPham_CTPhieuNhap", Storage="_CTPhieuNhaps", ThisKey="MaSP", OtherKey="MaSP")]
		public EntitySet<CTPhieuNhap> CTPhieuNhaps
		{
			get
			{
				return this._CTPhieuNhaps;
			}
			set
			{
				this._CTPhieuNhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BangSanPham_CTDonDatHang", Storage="_CTDonDatHangs", ThisKey="MaSP", OtherKey="MaSP")]
		public EntitySet<CTDonDatHang> CTDonDatHangs
		{
			get
			{
				return this._CTDonDatHangs;
			}
			set
			{
				this._CTDonDatHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiSanPham_BangSanPham", Storage="_LoaiSanPham", ThisKey="MaLoai", OtherKey="MaLoai", IsForeignKey=true)]
		public LoaiSanPham LoaiSanPham
		{
			get
			{
				return this._LoaiSanPham.Entity;
			}
			set
			{
				LoaiSanPham previousValue = this._LoaiSanPham.Entity;
				if (((previousValue != value) 
							|| (this._LoaiSanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiSanPham.Entity = null;
						previousValue.BangSanPhams.Remove(this);
					}
					this._LoaiSanPham.Entity = value;
					if ((value != null))
					{
						value.BangSanPhams.Add(this);
						this._MaLoai = value.MaLoai;
					}
					else
					{
						this._MaLoai = default(int);
					}
					this.SendPropertyChanged("LoaiSanPham");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaCC_BangSanPham", Storage="_NhaCC", ThisKey="MaNCC", OtherKey="MaNCC", IsForeignKey=true)]
		public NhaCC NhaCC
		{
			get
			{
				return this._NhaCC.Entity;
			}
			set
			{
				NhaCC previousValue = this._NhaCC.Entity;
				if (((previousValue != value) 
							|| (this._NhaCC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhaCC.Entity = null;
						previousValue.BangSanPhams.Remove(this);
					}
					this._NhaCC.Entity = value;
					if ((value != null))
					{
						value.BangSanPhams.Add(this);
						this._MaNCC = value.MaNCC;
					}
					else
					{
						this._MaNCC = default(int);
					}
					this.SendPropertyChanged("NhaCC");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaSX_BangSanPham", Storage="_NhaSX", ThisKey="MaNSX", OtherKey="MaNSX", IsForeignKey=true)]
		public NhaSX NhaSX
		{
			get
			{
				return this._NhaSX.Entity;
			}
			set
			{
				NhaSX previousValue = this._NhaSX.Entity;
				if (((previousValue != value) 
							|| (this._NhaSX.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhaSX.Entity = null;
						previousValue.BangSanPhams.Remove(this);
					}
					this._NhaSX.Entity = value;
					if ((value != null))
					{
						value.BangSanPhams.Add(this);
						this._MaNSX = value.MaNSX;
					}
					else
					{
						this._MaNSX = default(int);
					}
					this.SendPropertyChanged("NhaSX");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTSanPhams(CTSanPham entity)
		{
			this.SendPropertyChanging();
			entity.BangSanPham = this;
		}
		
		private void detach_CTSanPhams(CTSanPham entity)
		{
			this.SendPropertyChanging();
			entity.BangSanPham = null;
		}
		
		private void attach_CTPhieuNhaps(CTPhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.BangSanPham = this;
		}
		
		private void detach_CTPhieuNhaps(CTPhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.BangSanPham = null;
		}
		
		private void attach_CTDonDatHangs(CTDonDatHang entity)
		{
			this.SendPropertyChanging();
			entity.BangSanPham = this;
		}
		
		private void detach_CTDonDatHangs(CTDonDatHang entity)
		{
			this.SendPropertyChanging();
			entity.BangSanPham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BangPhieuNhap")]
	public partial class BangPhieuNhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaPN;
		
		private int _MaNCC;
		
		private System.DateTime _NgayNhap;
		
		private bool _Daxoa;
		
		private EntityRef<NhaCC> _NhaCC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPNChanging(int value);
    partial void OnMaPNChanged();
    partial void OnMaNCCChanging(int value);
    partial void OnMaNCCChanged();
    partial void OnNgayNhapChanging(System.DateTime value);
    partial void OnNgayNhapChanged();
    partial void OnDaxoaChanging(bool value);
    partial void OnDaxoaChanged();
    #endregion
		
		public BangPhieuNhap()
		{
			this._NhaCC = default(EntityRef<NhaCC>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaPN
		{
			get
			{
				return this._MaPN;
			}
			set
			{
				if ((this._MaPN != value))
				{
					this.OnMaPNChanging(value);
					this.SendPropertyChanging();
					this._MaPN = value;
					this.SendPropertyChanged("MaPN");
					this.OnMaPNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNCC", DbType="Int NOT NULL")]
		public int MaNCC
		{
			get
			{
				return this._MaNCC;
			}
			set
			{
				if ((this._MaNCC != value))
				{
					if (this._NhaCC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNCCChanging(value);
					this.SendPropertyChanging();
					this._MaNCC = value;
					this.SendPropertyChanged("MaNCC");
					this.OnMaNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNhap", DbType="DateTime NOT NULL")]
		public System.DateTime NgayNhap
		{
			get
			{
				return this._NgayNhap;
			}
			set
			{
				if ((this._NgayNhap != value))
				{
					this.OnNgayNhapChanging(value);
					this.SendPropertyChanging();
					this._NgayNhap = value;
					this.SendPropertyChanged("NgayNhap");
					this.OnNgayNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Daxoa", DbType="Bit NOT NULL")]
		public bool Daxoa
		{
			get
			{
				return this._Daxoa;
			}
			set
			{
				if ((this._Daxoa != value))
				{
					this.OnDaxoaChanging(value);
					this.SendPropertyChanging();
					this._Daxoa = value;
					this.SendPropertyChanged("Daxoa");
					this.OnDaxoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaCC_BangPhieuNhap", Storage="_NhaCC", ThisKey="MaNCC", OtherKey="MaNCC", IsForeignKey=true)]
		public NhaCC NhaCC
		{
			get
			{
				return this._NhaCC.Entity;
			}
			set
			{
				NhaCC previousValue = this._NhaCC.Entity;
				if (((previousValue != value) 
							|| (this._NhaCC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhaCC.Entity = null;
						previousValue.BangPhieuNhaps.Remove(this);
					}
					this._NhaCC.Entity = value;
					if ((value != null))
					{
						value.BangPhieuNhaps.Add(this);
						this._MaNCC = value.MaNCC;
					}
					else
					{
						this._MaNCC = default(int);
					}
					this.SendPropertyChanged("NhaCC");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
